### ISSUE TITLE
Error reported when import tensorly (version: 0.8.0) in Python 3.7

### ISSUE THREAD

**Issue by shuo-zhou** [tensorly/tensorly#479] opened 2023-01-17 17:44 UTC
In Pyhone 3.7, importing TensorLy, `import tensorly as tl`, will get the following error message:

```
from .generalised_inner_product import inner
  File "<fstring>", line 1
    (tensor1.shape=)
                  ^
SyntaxError: invalid syntax
```

The problem should be caused by the updates in the following lines

https://github.com/tensorly/tensorly/blob/8ff7e2950ca939c64641bfe0169e455f7cc59b56/tensorly/tenalg/core_tenalg/generalised_inner_product.py#L34

https://github.com/tensorly/tensorly/blob/8ff7e2950ca939c64641bfe0169e455f7cc59b56/tensorly/tenalg/core_tenalg/generalised_inner_product.py#L48

which only work in Python 3.8 and 3.9. Will TensorLy stop supporting Python 3.7 and 3.6?

**Comment by JeanKossaifi** [comment] 2023-01-17 17:54
Duplicate of #473 - it seems this is an issue for many, let's just use Python 3.7 compatible formatting for now.

**Comment by JeanKossaifi** [comment] 2023-01-17 17:56
Out of curiosity, @shuo-zhou, is there any reason in particular you still need to support Python 3.7?

**Comment by shuo-zhou** [comment] 2023-01-17 18:02
> Out of curiosity, @shuo-zhou, is there any reason in particular you still need to support Python 3.7?

Some users of our library running experiments on servers, where only old Python versions are available.

**Closed** 2023-01-24 00:54 UTC
