### ISSUE TITLE
Support TT decomposition using CUDA backend

### ISSUE THREAD

**Issue by JeremieMelo** [tensorly/tensorly#410] opened 2022-06-09 19:30 UTC
#### Is your feature request related to a problem? Please describe.
When performing decomposition, e.g., tensor_train using pytorch backend, it by default uses scipy.linalg.svd, which is very slow especially when the input tensor is on CUDA. 

#### Describe the solution you'd like
Consider using torch.linalg.svd for fast decomposition for CUDA Tensors

**Comment by cohenjer** [comment] 2022-06-13 15:25
Hi @JeremieMelo,
So this is kind of tricky. Tensorly is using `scipy.sparse.linalg.eigsh` and some post-processing to compute a "small" SVD, that is a SVD where only a few singular values/singular vectors are required. We could use a full SVD and truncate it but @JeanKossaifi wanted to avoid this option for speed/memory reasons. The problem is that as far as I know, only scipy.sparse has an implementation of `eigsh` (which itself calls LAPACK if I remember correctly). And scipy needs numpy arrays, thus the factors are recast as numpy arrays in `partial_svd` which is called in e.g. Tucker decomposition or Tensor Train decomposition.

However in your case, using full SVD and then truncating it could be faster, since you could use the backend's SVD and not recast the factors as numpy arrays, avoiding the break GPU support. You can tinker with this by modifying the `partial_svd` function in `tensorly.backend.core.py`.

**Comment by JeanKossaifi** [comment] 2022-06-13 18:01
@JeremieMelo @cohenjer we already have full GPU support - just pass for instance `svd= 'truncated_svd'` instead of `'numppy_svd'`. You can check available functions by printing `tensorly.SVD_FUNS`.  In particular you can also use, for PyTorch, `symeig_svd` and `randomized_svd`. 

As @cohenjer mentioned numpy_svd uses an efficient sparse SVD that is CPU only.

**Comment by cohenjer** [comment] 2022-06-14 06:33
Hey @JeanKossaifi I think there is still an issue with Tensor Train decomposition. In `tensorly.decomposition._tt.py`, partial_svd is used not svd, and there is no option to change default SVD like you are suggesting. I thought this was intended, but right now I do think we have no GPU support for the TT decomposition?

**Comment by cohenjer** [comment] 2022-07-04 09:57
I am reopening the issue since TT decomposition does not have GPU support.

**Comment by JeanKossaifi** [comment] 2022-07-15 18:47
Indeed, this is an oversight, we should always support other SVDs. Thanks for reopening @cohenjer.

**Comment by JeanKossaifi** [comment] 2022-10-31 00:59
Fixed in #453.

**Closed** 2022-10-31 04:21 UTC
Labels: bug
