### ISSUE TITLE
ValueError: matrix type must be 'f', 'd', 'F', or 'D'

### ISSUE THREAD

**Issue by mcg1969** [tensorly/tensorly#98] opened 2019-02-18 22:33 UTC
Running the `parafac` function in [this notebook from tensorly-notebooks](https://github.com/JeanKossaifi/tensorly-notebooks/blob/master/02_tensor_decomposition/cp_decomposition.ipynb) results in the following traceback. Replacing the `np.arange(24)` call with `np.arange(24, dtype='d')` fixes the problem.

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-c5e3bbd4ab85> in <module>
----> 1 factors = parafac(X, rank=2)

~/Repos/tensor_demo/envs/default/lib/python3.7/site-packages/tensorly/decomposition/candecomp_parafac.py in parafac(tensor, rank, n_iter_max, init, svd, tol, orthogonalise, random_state, verbose, return_errors, non_negative, mask)
    176     factors = initialize_factors(tensor, rank, init=init, svd=svd,
    177                                  random_state=random_state,
--> 178                                  non_negative=non_negative)
    179     rec_errors = []
    180     norm_tensor = tl.norm(tensor, 2)

~/Repos/tensor_demo/envs/default/lib/python3.7/site-packages/tensorly/decomposition/candecomp_parafac.py in initialize_factors(tensor, rank, init, svd, random_state, non_negative)
     99         factors = []
    100         for mode in range(tl.ndim(tensor)):
--> 101             U, _, _ = svd_fun(unfold(tensor, mode), n_eigenvecs=rank)
    102 
    103             if tensor.shape[mode] < rank:

~/Repos/tensor_demo/envs/default/lib/python3.7/site-packages/tensorly/backend/core.py in partial_svd(self, matrix, n_eigenvecs)
    668             if dim_1 < dim_2:
    669                 S, U = scipy.sparse.linalg.eigsh(
--> 670                     np.dot(matrix, matrix.T.conj()), k=n_eigenvecs, which='LM'
    671                 )
    672                 S = np.sqrt(S)

~/Repos/tensor_demo/envs/default/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py in eigsh(A, k, M, sigma, which, v0, ncv, maxiter, tol, return_eigenvectors, Minv, OPinv, mode)
   1661     params = _SymmetricArpackParams(n, k, A.dtype.char, matvec, mode,
   1662                                     M_matvec, Minv_matvec, sigma,
-> 1663                                     ncv, v0, maxiter, which, tol)
   1664 
   1665     with _ARPACK_LOCK:

~/Repos/tensor_demo/envs/default/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py in __init__(self, n, k, tp, matvec, mode, M_matvec, Minv_matvec, sigma, ncv, v0, maxiter, which, tol)
    511 
    512         _ArpackParams.__init__(self, n, k, tp, mode, sigma,
--> 513                                ncv, v0, maxiter, which, tol)
    514 
    515         if self.ncv > n or self.ncv <= k:

~/Repos/tensor_demo/envs/default/lib/python3.7/site-packages/scipy/sparse/linalg/eigen/arpack/arpack.py in __init__(self, n, k, tp, mode, sigma, ncv, v0, maxiter, which, tol)
    319 
    320         if tp not in 'fdFD':
--> 321             raise ValueError("matrix type must be 'f', 'd', 'F', or 'D'")
    322 
    323         if v0 is not None:

ValueError: matrix type must be 'f', 'd', 'F', or 'D'
```

**Comment by JeanKossaifi** [comment] 2019-02-20 23:49
Thanks for reporting!
The issue is indeed the dtype, arange is int64 by default but it seems that eigsh expects floats.

**Comment by JeanKossaifi** [comment] 2019-04-16 11:18
Fixed in https://github.com/JeanKossaifi/tensorly-notebooks/commit/9b711e3601ba45241c60af0f8efa0210cadcd327

**Closed by JeanKossaifi** 2019-04-16 11:18 UTC
Labels: bug
